version: "3"

services:
  mysql:
    image: "bitnami/mysql:5.7"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=db_app
      # - MYSQL_ROOT_PASSWORD=pass
    ports:
      - 3306:3306

  phpmyadmin:
    image: bitnami/phpmyadmin:5
    ports:
      - "80:8080"
      - "443:8443"
    depends_on:
      - mysql
    environment:
      - DATABASE_HOST=mysql

  app:
    tty: true
    image: bitnami/laravel:5.8.0
    environment:
      - DB_HOST=mysql
      - DB_USERNAME=root
      - DB_DATABASE=db_app
      # - DB_PASSWORD=pass
    depends_on:
      - mysql
    ports:
      - 3000:3000
    volumes:
      - ./:/app

